version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ops_db
    restart: always
    environment:
      POSTGRES_USER: opsadmin
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: opsmanager
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: ops_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://opsadmin:secretpass@db:5432/opsmanager
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: ops_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5000
    depends_on:
      - backend

volumes:
  db_data:
